<?php
/**
 * Dynamic CSS Generator - White-Label SaaS
 * Generates CSS with brand colors from configuration.
 * 
 * @package WhiteLabel\Assets
 */

// Set correct content type and caching headers
header('Content-Type: text/css; charset=utf-8');
header('Cache-Control: public, max-age=86400'); // Cache for 24 hours
header('X-Content-Type-Options: nosniff');

// Load branding configuration
require_once __DIR__ . '/../../config/branding.php';

// Get colors from brand config
$primary = brand('primary');
$primaryDark = brand('primary_dark');
$secondary = brand('secondary');
$accent = brand('accent');
$bgColor = brand('bg_color');
$textMain = brand('text_main');
$textMuted = brand('text_muted');
$fontHeading = brand('font_heading');
$fontBody = brand('font_body');
?>
/* =====================================================
   WHITE-LABEL DYNAMIC CSS
   Generated by: style.php
   ===================================================== */

/* === CSS Custom Properties === */
:root {
    /* Brand Colors */
    --primary-color: <?php echo $primary; ?>;
    --primary-dark: <?php echo $primaryDark; ?>;
    --secondary-color: <?php echo $secondary; ?>;
    --accent-color: <?php echo $accent; ?>;
    
    /* Transparency Variants */
    --primary-10: <?php echo hexToRgba($primary, 0.1); ?>;
    --primary-15: <?php echo hexToRgba($primary, 0.15); ?>;
    --primary-20: <?php echo hexToRgba($primary, 0.2); ?>;
    --primary-50: <?php echo hexToRgba($primary, 0.5); ?>;
    
    /* Background & Text */
    --bg-color: <?php echo $bgColor; ?>;
    --text-main: <?php echo $textMain; ?>;
    --text-muted: <?php echo $textMuted; ?>;
    
    /* Card & Component */
    --card-bg: #ffffff;
    --card-border: #e2e8f0;
    --card-shadow: 0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px -1px rgba(0, 0, 0, 0.1);
    
    /* Borders & Inputs */
    --input-border: #cbd5e1;
    --input-focus: var(--primary-color);
}

/* === Base Styles === */
body {
    font-family: <?php echo $fontBody; ?>;
    background-color: var(--bg-color);
    color: var(--text-main);
    line-height: 1.6;
}

h1, h2, h3, h4, h5, h6, .navbar-brand {
    font-family: <?php echo $fontHeading; ?>;
    font-weight: 600;
}

/* === Primary Button === */
.btn-primary {
    background-color: var(--primary-color);
    border-color: var(--primary-color);
    transition: all 0.2s ease;
}

.btn-primary:hover, .btn-primary:focus {
    background-color: var(--primary-dark);
    border-color: var(--primary-dark);
    transform: translateY(-1px);
    box-shadow: 0 4px 12px var(--primary-50);
}

.btn-primary:active {
    transform: translateY(0);
}

/* === Outline Button === */
.btn-outline-primary {
    color: var(--primary-color);
    border-color: var(--primary-color);
}

.btn-outline-primary:hover {
    background-color: var(--primary-color);
    border-color: var(--primary-color);
    color: white;
}

/* === Cards === */
.card {
    border: none;
    border-radius: 12px;
    box-shadow: var(--card-shadow);
    background-color: var(--card-bg);
    transition: box-shadow 0.2s ease, transform 0.2s ease;
}

.card:hover {
    box-shadow: 0 10px 25px -5px rgba(0, 0, 0, 0.1);
}

/* === Text Colors === */
.text-primary {
    color: var(--primary-color) !important;
}

.text-accent {
    color: var(--accent-color) !important;
}

/* === Links === */
a {
    color: var(--primary-color);
    text-decoration: none;
    transition: color 0.2s ease;
}

a:hover {
    color: var(--primary-dark);
}

/* === Form Inputs === */
.form-control:focus, .form-select:focus {
    border-color: var(--primary-color);
    box-shadow: 0 0 0 3px var(--primary-20);
}

/* === Wizard Step Dots === */
.step-dot {
    width: 40px;
    height: 40px;
    border-radius: 50%;
    background: #e5e7eb;
    border: 2px solid #d1d5db;
    display: flex;
    align-items: center;
    justify-content: center;
    font-weight: 600;
    color: #6b7280;
    z-index: 10;
    transition: all 0.3s ease;
}

.step-dot.active {
    background: var(--primary-color);
    border-color: var(--primary-color);
    color: white;
    box-shadow: 0 0 0 4px var(--primary-20);
}

.step-dot.completed {
    background: var(--accent-color);
    border-color: var(--accent-color);
    color: white;
}

/* === Time Slot Buttons === */
.btn-time {
    width: 100%;
    background: #f8fafc;
    border: 1px solid var(--input-border);
    color: var(--text-main);
    padding: 0.5rem;
    border-radius: 8px;
    transition: all 0.2s ease;
}

.btn-time:hover:not(:disabled) {
    border-color: var(--primary-color);
    background: var(--primary-10);
    color: var(--primary-dark);
}

.btn-time.active {
    background: var(--primary-color);
    border-color: var(--primary-color);
    color: white;
}

.btn-time:disabled {
    opacity: 0.4;
    cursor: not-allowed;
    text-decoration: line-through;
}

/* === Tables === */
.table-hover tbody tr:hover {
    background-color: var(--primary-10);
}

/* === Navbar === */
.navbar {
    background-color: var(--card-bg);
    box-shadow: 0 1px 3px rgba(0, 0, 0, 0.05);
}

.navbar-brand {
    font-weight: 700;
    color: var(--text-main);
}

/* === Alerts === */
.alert-success {
    background-color: <?php echo hexToRgba($accent, 0.1); ?>;
    border-color: <?php echo $accent; ?>;
    color: <?php echo $accent; ?>;
}

/* === Radio Card Selection === */
.btn-check:checked + label.card {
    background-color: var(--primary-10);
    border: 2px solid var(--primary-color);
    box-shadow: 0 0 0 3px var(--primary-20);
}

/* === Form Switch === */
.form-check-input:checked {
    background-color: var(--primary-color);
    border-color: var(--primary-color);
}

/* === Animations === */
@keyframes fadeIn {
    from {
        opacity: 0;
        transform: translateY(10px);
    }
    to {
        opacity: 1;
        transform: translateY(0);
    }
}

.fade-in {
    animation: fadeIn 0.4s ease-out forwards;
}

/* === Cursor Helper === */
.cursor-pointer {
    cursor: pointer;
}

/* === Wizard Container === */
.wizard-container {
    max-width: 800px;
    margin: 0 auto;
}

/* === Step Content === */
.step-content {
    display: none;
    animation: fadeIn 0.4s ease;
}

.step-content.active {
    display: block;
}

/* === Loading Overlay === */
.loading-overlay {
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background: rgba(255, 255, 255, 0.95);
    z-index: 9999;
    display: flex;
    align-items: center;
    justify-content: center;
    flex-direction: column;
}

.loading-overlay .spinner-border {
    color: var(--primary-color);
    width: 3rem;
    height: 3rem;
}

/* === Badge Variants === */
.badge-primary {
    background-color: var(--primary-color);
    color: white;
}

.badge-accent {
    background-color: var(--accent-color);
    color: white;
}

/* === Footer === */
footer {
    background-color: var(--card-bg);
    border-top: 1px solid var(--card-border);
}

/* === Responsive === */
@media (max-width: 768px) {
    .step-dot {
        width: 32px;
        height: 32px;
        font-size: 0.875rem;
    }
    
    .wizard-container {
        padding: 0 1rem;
    }
}
